

all:
	gcc assignment0.c -o assignment0
	gcc assignment1.c -o assignment1
	gcc assignment2.c -o assignment2
	gcc assignment3.c -o assignment3
	gcc assignment4.c -o assignment4
test:
	./assignment0
	./assignment1
	./assignment2
	./assignment3
	./assignment4
