

all:
	gcc assignment1.c -o assignment1
	gcc assignment2.c -o assignment2
	gcc assignment3.c -o assignment3
	gcc assignment3_v2.c -o assignment3_v2

test:
	./assignment1
	./assignment2
	./assignment3
	./assignment3_v2
