


all:
	gcc copy_file_contents.c -o copy
	gcc file_truncation.c -o trunc
	gcc reverse_file_reader.c -o reverse_reader
	gcc append.c -o append
	gcc sparse_file.c -o sparse
	gcc overwrie_lseek.c -o overwrite
